# PostgreSQL — variables de entorno del docker-compose.yml
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/agenthub}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:agenthub}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:agenthub123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto
server.port=8080

# JWT
jwt.secret=agenthub-super-secret-key-2024-minimum-32-characters-long
jwt.expiration=86400000

# configuracion de openrouter
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.api.key=${OPENROUTER_API_KEY}

# Stripe — clave secreta leída desde .env (nunca hardcodear aquí)
stripe.secret.key=${STRIPE_SECRET_KEY}

#openrouter.api.model=anthropic/claude-3-haiku

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# url front end para link del mail
app.frontend.url={FRONTEND_URL:http://localhost:3000}